'use client'
import React from 'react';
import Navbarpage from './Navbarpage/page';
import Link from 'next/link';
import './globals.css';
import { Inter } from 'next/font/google';
import StoreProvider from './Store/Provider';
const inter = Inter({ subsets: ['latin'] });
import { usePathname } from 'next/navigation';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  const pathName = usePathname();
  
 
  const excludedPaths = ["/",'/Register'];

  const showNavbar = !excludedPaths.includes(pathName);

  return (
    <html lang="en">
     <head>
    <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.2.1/css/fontawesome.min.css"
          integrity="sha384-QYIZto+st3yW+o8+5OHfT6S482Zsvz2WfOzpFSXMF9zqeLcFV0/wlZpMtyFcZALm"
          crossorigin="anonymous"
        />
        <link href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.2.1/css/fontawesome.min.css" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
          integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer"
        />
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous"/>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>

      </head>
      <body className={inter.className}>
      <StoreProvider>
          {showNavbar ? <Navbarpage /> 
          :<div className='text-primary'><Link href="/Homepage">back to Dashboard</Link></div>} 
          {children}
        </StoreProvider>
     </body>
    </html>
  )
}
